feat: add response status editable by loader
deco-cx/deco pull request #460
Opened 2023-10-02 14:47 UTC by IncognitaDev

When a search return 0 products, some SEO agencies demand the page return to be 404 as response status.
In antive vtex stores not found PDPs return 404 as a reponse status (legacy and storefront)

This PR add Status in ctx to be editable by loader.

Use Case: 

Do a invalid search
in inline loader, check the product return length
if 0, change the status to 404 with `ctx.response.status`

2023-10-02 16:02 UTC, mcandeia requested changes
Can you provide a site link which I can assure that the behavior is working properly?

2023-10-02 16:02 UTC, mcandeia commented on routes/_middleware.ts
> +      [400, 404, 500].includes(initialResponse.status)
I suggest you to extract the variable `status` and reuse it here to keep consistency across usages.

2023-10-02 16:55 UTC, IncognitaDev commented
> Can you provide a site link which I can assure that the behavior is working properly?

I dont know how to link a fork in my site but i have this repo with a example implemented, you can clone and link this deco version to view the behaviour .

https://github.com/deco-sites/vtexlegacydebug

2023-10-03 21:12 UTC, mcandeia approved these changes

2023-10-03 21:13 UTC, merged