useScript breaking when called in the browser
deco-cx/deco pull request #859
Opened 2024-10-09 19:12 UTC by saymondamasio

Do not break if the `useScript` is called inside an island.

Because `Deno` does not exist on the client side.

2024-10-10 13:37 UTC, viktormarinho commented
Some things to note here:

- $fresh/runtime probably should not be imported in this file, since you can use it independently from the fresh setup
- useScript should probably not be used in the browser at all; it is importing terser

2024-11-26 13:14 UTC, matheusgr commented
useScript must fail if run in client side. Its a server side only thing to do.

Maybe you can give a warning and don't run it on client side instead.

2024-11-26 13:15 UTC, matheusgr requested changes

2024-11-26 13:15 UTC, matheusgr commented on hooks/useScript.ts
> +const verbose = !IS_BROWSER && !!Deno.env.get("SCRIPT_MINIFICATION_DEBUG");
I believe that this function should not run client side.

Maybe if it is run at clientSide, throw an exception and stop it execution.

2026-05-14 21:13 UTC, closed without merging